#!/usr/bin/env python

import math

import rospy
import tf2_ros
from std_msgs.msg import Time
from geometry_msgs.msg import TransformStamped, PoseStamped

# Global Variables
tfbr = None
pub_found = None

camera_name = "camera"
target_name = "target"

def send_tf_target(msg_in):
	# Generate our "found" timestamp
	time_found = rospy.Time.now()

	# Create a transform arbitrarily in the
	# camera frame
	t = TransformStamped()
	t.header.stamp = time_found
	t.header.frame_id = camera_name
	t.child_frame_id = target_name
	
	
    # In here we need a code to get the target location relative to the camera (Perhaps solve PnP)

    # Once we know where the target is, relative to the camera frame, we create and sent that transform (relative position target to camera)
	t.transform.translation.x = msg_in.transform.translation.x
	t.transform.translation.y = msg_in.transform.translation.y
	t.transform.translation.z = msg_in.transform.translation.z
	t.transform.rotation.x = 0.0
	t.transform.rotation.y = 0.0
	t.transform.rotation.z = 0.0
	t.transform.rotation.w = 1.0
	

	# Send the transformation to TF
	# and "found" timestamp to localiser
	tfbr.sendTransform(t)
	pub_found.publish(time_found)

if __name__ == '__main__':
	rospy.init_node('tf2_broadcaster_target')
	rospy.loginfo("tf2_broadcaster_target sending target found...")

	# Setup tf2 broadcaster and timestamp publisher
	tfbr = tf2_ros.TransformBroadcaster()
	pub_found = rospy.Publisher('/emulated_uav/target_found', Time, queue_size=10)

	# Subscriber to listen to the target detection topic for pose updates
	rospy.Subscriber('/processed_aruco/pose', PoseStamped, send_tf_target)
	# Give the nodes a few seconds to configure
	rospy.sleep(rospy.Duration(2))

	# Send out our target messages
	

	# Give the nodes a few seconds to transmit data
	# then we can exit
	rospy.sleep(rospy.Duration(2))
	rospy.loginfo("tf2_broadcaster_target sent TF and timestamp")
	rospy.spin()